### Get all company list
GET http://localhost:4000/api/users/company/getall

### Get one company
GET http://localhost:4000/api/users/company/getone/34

### Save a company
POST http://localhost:4000/api/users/company/save
Content-Type: application/json

{
    "correo":"empresa1@gmail.com",
    "clave":"12345678",
   "nombreComercial":"Draxnmaier",
   "calle":"Lazaro Rodriguz",
   "nEmpresa":25,
   "colonia":"Arbide",
   "cp": 4221,
   "municipio":"Lagos de moreno",
   "estado": "Jalisco",
   "Telefono": 32323,
   "tipo_empresa":"Ganadera",
   "tamaño":"Grande",
   "actividad_economica": "Pesca"
}

### Update a company
PUT http://localhost:4000/api/users/company/update/33
Content-Type: application/json

{
    "correo":"empresa2@gmail.com",
    "clave":"12345678",
   "nombreComercial":"Drax and Maier",
   "calle":"Lazaro Rodriguz",
   "nEmpresa":25,
   "colonia":"Arbide",
   "cp": 4221,
   "municipio":"Lagos de moreno",
   "estado": "Jalisco",
   "Telefono": 32323,
   "tipo_empresa":"Ganadera",
   "tamaño":"Grande",
   "actividad_economica": "Pesca"
}

### Delete a company
DELETE http://localhost:4000/api/users/company/delete/33
Content-Type: application/json

