### Get all user list
GET http://localhost:4000/api/users/getall

### Get one user
GET http://localhost:4000/api/users/getone/2

### Save an user
POST http://localhost:4000/api/users/save
Content-Type: application/json

{
    "correo":"admin@gmail.com",
    "clave":"12345678",
    "fk_rol": 1
}

### Update an user
PUT http://localhost:4000/api/users/update/22
Content-Type: application/json

{
    "correo":"asdasd@gmail.com"
}

### Delete an user
DELETE http://localhost:4000/api/users/delete/5
Content-Type: application/json

