### get all sections
GET http://localhost:4000/api/graduated/survey/sections
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY29ycmVvIjoianVhbkBnbWFpbC5jb20iLCJma19yb2wiOjIsImlhdCI6MTY0Njg4NTIwOX0.--6_spm8D0PvMpmGxDVCJG1wUR5NMInOn5InkvSx76U

### get only one section
GET http://localhost:4000/api/graduated/survey/sections/getone/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY29ycmVvIjoianVhbkBnbWFpbC5jb20iLCJma19yb2wiOjIsImlhdCI6MTY0Njg4NTIwOX0.--6_spm8D0PvMpmGxDVCJG1wUR5NMInOn5InkvSx76U


### Get all questions from a section, if id is not provided we get all questions of each section
GET http://localhost:4000/api/graduated/survey/questions/section/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY29ycmVvIjoianVhbkBnbWFpbC5jb20iLCJma19yb2wiOjIsImlhdCI6MTY0Njg4NTIwOX0.--6_spm8D0PvMpmGxDVCJG1wUR5NMInOn5InkvSx76U

### to get all  users answer from a section 
GET http://localhost:4000/api/graduated/survey/section/1/answers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY29ycmVvIjoianVhbkBnbWFpbC5jb20iLCJma19yb2wiOjIsImlhdCI6MTY0Njg4NTIwOX0.--6_spm8D0PvMpmGxDVCJG1wUR5NMInOn5InkvSx76U


### to save all user answers from section 1 
POST http://localhost:4000/api/graduated/survey/section1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY29ycmVvIjoianVhbkBnbWFpbC5jb20iLCJma19yb2wiOjIsImlhdCI6MTY0Njg4NTIwOX0.--6_spm8D0PvMpmGxDVCJG1wUR5NMInOn5InkvSx76U

{
 "respuesta1":"Mala",
 "respuesta2":"Buenos",
 "respuesta3":"Mala",
 "respuesta4":"Muy Buena",
 "respuesta5":"Muy buena",
 "respuesta6":"Buena"
}


### to save all user answers from section 2, if user is studing
POST http://localhost:4000/api/graduated/survey/section2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY29ycmVvIjoianVhbkBnbWFpbC5jb20iLCJma19yb2wiOjIsImlhdCI6MTY0Njg4NTIwOX0.--6_spm8D0PvMpmGxDVCJG1wUR5NMInOn5InkvSx76U

{
    "respuesta1":"Estudia",
    "tipo_estudio":"Maestria",
    "especialidad_institucion":"Tejuinos"  
}


### to save all user answers from section 2, if user works
POST http://localhost:4000/api/graduated/survey/section2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY29ycmVvIjoianVhbkBnbWFpbC5jb20iLCJma19yb2wiOjIsImlhdCI6MTY0Njg4NTIwOX0.--6_spm8D0PvMpmGxDVCJG1wUR5NMInOn5InkvSx76U

{
    "respuesta1":"Trabaja",
    "tiempo_primer_empleo": "6 meses",
    "medio_obtener_empleo": "Bolsa de trabajo tec",
    "requisitos_contratacion": "Titulo y programacion web react",
    "idioma_utilizado": "Ingles",
    "idioma_hablar": 100,
    "idioma_escribir": 100,
    "idioma_leer": 100,
    "idioma_escuchar": 100,
    "antiguedad_empleo":"12 meses",
    "año_ingreso":"2020",
    "salario":"Menos de cinco",
    "nivel_jerarquico":"Tecnico",
    "condicion_trabajo":"Contrato",
    "relacion_trabajo_formacion": 20,
    "organismo_empresa":"Publico",
    "actividad_principal_empresa":"Vender cables",
    "razon_social":"Stanlet",
    "calle":"Lazaro cardenas",
    "numero": 34,
    "colonia":"Lomas de lagos",
    "cp": 47510,
    "ciudad":"Lagos de moreno",
    "municipio":"Lagos de moreno",
    "estado":"Jalisco",
    "telefono_empresa": 1234567890,
    "telefono_ext_empresa": 1234567890,
    "fax_empresa": 1987654321,
    "email_empresa":"empresa@gmail.com",
    "tipo_sector_empresa":"Primario",
    "sector_empresa":"Minero",
    "tamaño_empresa":"Mediana (101-500)"
}

### to save all user answers from section 2, if user works and study
POST http://localhost:4000/api/graduated/survey/section2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY29ycmVvIjoianVhbkBnbWFpbC5jb20iLCJma19yb2wiOjIsImlhdCI6MTY0Njg4NTIwOX0.--6_spm8D0PvMpmGxDVCJG1wUR5NMInOn5InkvSx76U

{
    "respuesta1":"Estudia y trabaja",
    "tipo_estudio":"Maestria",
    "especialidad_institucion":"Tejuinos",
    "tiempo_primer_empleo": "6 meses",
    "medio_obtener_empleo": "Bolsa de trabajo tec",
    "requisitos_contratacion": "Titulo y programacion web react",
    "idioma_utilizado": "Ingles",
    "idioma_hablar": 100,
    "idioma_escribir": 100,
    "idioma_leer": 100,
    "idioma_escuchar": 100,
    "antiguedad_empleo":"12 meses",
    "año_ingreso":"2020",
    "salario":"Menos de cinco",
    "nivel_jerarquico":"Tecnico",
    "condicion_trabajo":"Contrato",
    "relacion_trabajo_formacion": 20,
    "organismo_empresa":"Publico",
    "actividad_principal_empresa":"Vender cables",
    "razon_social":"Stanlet",
    "calle":"Lazaro cardenas",
    "numero": 34,
    "colonia":"Lomas de lagos",
    "cp": 47510,
    "ciudad":"Lagos de moreno",
    "municipio":"Lagos de moreno",
    "estado":"Jalisco",
    "telefono_empresa": 1234567890,
    "telefono_ext_empresa": 1234567890,
    "fax_empresa": 1987654321,
    "email_empresa":"empresa@gmail.com",
    "tipo_sector_empresa":"Primario",
    "sector_empresa":"Minero",
    "tamaño_empresa":"Mediana (101-500)"
}

### to save all user answers from section 2, if dont work and dont study
POST http://localhost:4000/api/graduated/survey/section2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY29ycmVvIjoianVhbkBnbWFpbC5jb20iLCJma19yb2wiOjIsImlhdCI6MTY0Njg4NTIwOX0.--6_spm8D0PvMpmGxDVCJG1wUR5NMInOn5InkvSx76U

{
    "respuesta1":"No estudia ni trabaja"
}

### to save all user answer from section 3
POST http://localhost:4000/api/graduated/survey/section3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY29ycmVvIjoianVhbkBnbWFpbC5jb20iLCJma19yb2wiOjIsImlhdCI6MTY0Njg4NTIwOX0.--6_spm8D0PvMpmGxDVCJG1wUR5NMInOn5InkvSx76U

{
    "respuesta1":"Deficiente",
    "respuesta2":"Bueno",
    "respuesta3":"Bueno",
    "area_estudio": 2,
    "titulacion": 5,
    "experiencia_laboral": 5,
    "competencia_laboral": 5,
    "posicionamiento_institucion_egreso": 2,
    "conocimiento_idiomas_extranjeros": 3,
    "recomendaciones": 1,
    "personalidad": 2,
    "capacidad_liderazgo": 4,
    "otros": 3
}

### to save all user answer from section 4
POST http://localhost:4000/api/graduated/survey/section4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY29ycmVvIjoianVhbkBnbWFpbC5jb20iLCJma19yb2wiOjIsImlhdCI6MTY0Njg4NTIwOX0.--6_spm8D0PvMpmGxDVCJG1wUR5NMInOn5InkvSx76U

{
    "respuesta1":"Si",
    "cursos":"Programacion web",
    "respuesta2":"Si",
    "posgrado":"Redes"
}

### to save all user answer from section 5
POST http://localhost:4000/api/graduated/survey/section5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY29ycmVvIjoianVhbkBnbWFpbC5jb20iLCJma19yb2wiOjIsImlhdCI6MTY0Njg4NTIwOX0.--6_spm8D0PvMpmGxDVCJG1wUR5NMInOn5InkvSx76U

{
    "respuesta1":"Si",
    "organizaciones_sociales":"La Onu",
    "respuesta2":"Si",
    "organismos_profesionistas":"No se que es",
    "respuesta3":"Si"
}

### to save all user answer from section 6
POST http://localhost:4000/api/graduated/survey/section6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY29ycmVvIjoianVhbkBnbWFpbC5jb20iLCJma19yb2wiOjIsImlhdCI6MTY0Njg4NTIwOX0.--6_spm8D0PvMpmGxDVCJG1wUR5NMInOn5InkvSx76U

{
    "respuesta1":"Mejorar las mac para aprender mejor desarrolo mobil ios"
}

### to list the other aspects that the user believes that are valuable for the company
GET http://localhost:4000/api/graduated/survey/section3/others-aspects/getall
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY29ycmVvIjoianVhbkBnbWFpbC5jb20iLCJma19yb2wiOjIsImlhdCI6MTY0Njg4NTIwOX0.--6_spm8D0PvMpmGxDVCJG1wUR5NMInOn5InkvSx76U


### to save or edit other aspects that the user believes that are valuable for the company
POST http://localhost:4000/api/graduated/survey/section3/others-aspects/save
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY29ycmVvIjoianVhbkBnbWFpbC5jb20iLCJma19yb2wiOjIsImlhdCI6MTY0Njg4NTIwOX0.--6_spm8D0PvMpmGxDVCJG1wUR5NMInOn5InkvSx76U

{
    "aspecto":"Habilidades blandas",
    "valoracion": 2
}


### to delete other aspects that the user believes that are valuable for the company
DELETE http://localhost:4000/api/graduated/survey/section3/others-aspects/delete/:aspect_id




