### Get all company profile list
GET http://localhost:4000/api/profile/company/getall

### Get one company profile
GET http://localhost:4000/api/profile/company/getone/2

### Save a company profile
POST http://localhost:4000/api/profile/company/save
Content-Type: application/json

{
    "correo":"admin003345@gmail.com",
    "clave":"12345678",
    "fk_rol": 1
}

### Update a company profile
PUT http://localhost:4000/api/profile/company/update/22
Content-Type: application/json

{
    "correo":"asdasd@gmail.com"
}

### Delete a company profile
DELETE http://localhost:4000/api/profile/company/delete/5
Content-Type: application/json

