### Get all graduated profile list
GET http://localhost:4000/api/profile/graduated/getall

### Get one graduated profile
GET http://localhost:4000/api/profile/graduated/getone/2

### Save a graduated profile
POST http://localhost:4000/api/profile/graduated/save
Content-Type: application/json

{
    "correo":"admin003345@gmail.com",
    "clave":"12345678",
    "fk_rol": 1
}

### Update a graduated profile
PUT http://localhost:4000/api/profile/graduated/update/22
Content-Type: application/json

{
    "correo":"asdasd@gmail.com"
}

### Delete a graduated profile
DELETE http://localhost:4000/api/profile/graduated/delete/5
Content-Type: application/json

